# Generated by Django 3.0.6 on 2020-05-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieReview', '0002_auto_20200531_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_detail',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
